// <auto-generated />
using System;
using System.Collections.Generic;
using CometHandler.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CometHandler.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250604125011_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CometHandler.Models.Comet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ComputedRegionCbhkFwbd")
                        .HasColumnType("text");

                    b.Property<string>("ComputedRegionNnqa25f4")
                        .HasColumnType("text");

                    b.Property<string>("Fall")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Mass")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordedClassification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecorderLatitude")
                        .HasColumnType("text");

                    b.Property<string>("RecorderLongitude")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Year")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RecordedClassification");

                    b.HasIndex("Year");

                    b.ToTable("Comets");
                });

            modelBuilder.Entity("CometHandler.Models.Comet", b =>
                {
                    b.OwnsOne("CometHandler.Models.GeoLocation", "Geolocation", b1 =>
                        {
                            b1.Property<string>("CometId")
                                .HasColumnType("text");

                            b1.PrimitiveCollection<List<double>>("Coordinates")
                                .IsRequired()
                                .HasColumnType("double precision[]");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CometId");

                            b1.ToTable("Comets");

                            b1.WithOwner()
                                .HasForeignKey("CometId");
                        });

                    b.Navigation("Geolocation");
                });
#pragma warning restore 612, 618
        }
    }
}
